### ISSUE TITLE
openApp redirects to playstore even if the app is installed

### ISSUE THREAD

**Issue by marcchiu** [Akora-IngDKB/app_launcher#2]
HELP!!! Tried calling AppLauncher.openApp to call whatsapp already installed and used on my phone with the following code, but the os will redirects to playstore. A toast message pops up saying "No app found with ID com.whatsapp."

**Calling com.android.settings worked fine though.**

`void _open() async {
    print('Calling');
    await AppLauncher.openApp(
      androidApplicationId: "com.whatsapp",
    );
  }`

debug message:
`I/flutter ( 4608): Redirecting to Google Play Store as the app is not present on the device
I/ViewRootImpl@e34559f[MainActivity]( 4608): MSG_WINDOW_FOCUS_CHANGED 0 1
I/SurfaceControl( 4608): release : mNativeObject = -5476376660460953200 - Surface(name=Surface(name=6d0ad5e InputMethod)/@0x939be0c - animation-leash)/@0x1fb5811 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
I/SurfaceControl( 4608): nativeRelease nativeObject s[-5476376660460953200]
I/SurfaceControl( 4608): nativeRelease nativeObject e[-5476376660460953200]
I/SurfaceControl( 4608): release : mNativeObject = -5476376660460958304 - Surface(name=Surface(name=526bbff NavigationBar0)/@0x17caacb - animation-leash)/@0xaffdd76 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
I/SurfaceControl( 4608): nativeRelease nativeObject s[-5476376660460958304]
I/SurfaceControl( 4608): nativeRelease nativeObject e[-5476376660460958304]
I/SurfaceControl( 4608): release : mNativeObject = -5476376660461223184 - Surface(name=Surface(name=2286016 StatusBar)/@0xff78b78 - animation-leash)/@0x3af6f77 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
I/SurfaceControl( 4608): nativeRelease nativeObject s[-5476376660461223184]
I/SurfaceControl( 4608): nativeRelease nativeObject e[-5476376660461223184]`

**Comment by Chonli** [comment]
If you have a android 11 or more, you need to add permission to manifest 
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />`

it's explain on package [device_apps](https://pub.dev/packages/device_apps) use internal by app launcher

**Comment by goops17** [comment]
@marcchiu  you can check my fork https://github.com/goops17/app_launcher, I have updated it to use QUERY_ALL_PACKAGES
